import type { CSSProperties } from 'react';

export const catppuccinMocha: Record<string, CSSProperties> = {
  'code[class*="language-"]': {
    color: '#cdd6f4',
    background: 'none',
    fontFamily: "Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace",
    textAlign: 'left',
    whiteSpace: 'pre-wrap',
    wordSpacing: 'normal',
    wordBreak: 'break-word',
    wordWrap: 'break-word',
    lineHeight: '1.5',
    tabSize: 4,
    hyphens: 'none',
  },
  'pre[class*="language-"]': {
    color: '#cdd6f4',
    background: '#1e1e2e',
    fontFamily: "Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace",
    textAlign: 'left',
    whiteSpace: 'pre-wrap',
    wordSpacing: 'normal',
    wordBreak: 'break-word',
    wordWrap: 'break-word',
    lineHeight: '1.5',
    tabSize: 4,
    hyphens: 'none',
    padding: '1em',
    margin: '0.5em 0',
    overflow: 'visible',
    borderRadius: '0.5em',
  },
  comment: { color: '#6c7086', fontStyle: 'italic' },
  prolog: { color: '#6c7086' },
  doctype: { color: '#6c7086' },
  cdata: { color: '#6c7086' },
  punctuation: { color: '#9399b2' },
  property: { color: '#f38ba8' },
  tag: { color: '#89b4fa' },
  boolean: { color: '#fab387' },
  number: { color: '#fab387' },
  constant: { color: '#fab387' },
  symbol: { color: '#f9e2af' },
  deleted: { color: '#f38ba8' },
  selector: { color: '#a6e3a1' },
  'attr-name': { color: '#f9e2af' },
  string: { color: '#a6e3a1' },
  char: { color: '#a6e3a1' },
  builtin: { color: '#f38ba8' },
  inserted: { color: '#a6e3a1' },
  operator: { color: '#89dceb' },
  entity: { color: '#89b4fa', cursor: 'help' },
  url: { color: '#89dceb' },
  '.language-css .token.string': { color: '#89dceb' },
  '.style .token.string': { color: '#89dceb' },
  variable: { color: '#cdd6f4' },
  atrule: { color: '#f9e2af' },
  'attr-value': { color: '#a6e3a1' },
  function: { color: '#89b4fa' },
  'class-name': { color: '#f9e2af' },
  keyword: { color: '#cba6f7' },
  regex: { color: '#f5c2e7' },
  important: { color: '#fab387', fontWeight: 'bold' },
  bold: { fontWeight: 'bold' },
  italic: { fontStyle: 'italic' },
};
